model_name : SDNE
version : wk1.0
task : recall
topN_final : 100
top_k_user : 10
top_k_item : 10
train_params:
  batch_size : 32
  epochs : 50
  verbose : 2

model_params:
  hidden_size: [32,16]