model_name : AutoInt
version : wk1.0
batch_size : 256
n_epoch : 10
lr : 0.001
emb_size : 8
task : ctr

params:
  att_layer_num : 3
  att_embedding_size : 8
  att_head_num : 2
  att_res : True
  dnn_hidden_units : [256,256]
  dnn_activation : 'relu'
  l2_reg_linear : 0.00001
  l2_reg_embedding : 0.00001
  l2_reg_dnn : 0
  dnn_use_bn : False
  dnn_dropout : 0