# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoRecall/proto/common_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AutoRecall/proto/common_param.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\020AutoRecall/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#AutoRecall/proto/common_param.proto\x12\x05proto\"T\n\nQueryField\x12\x11\n\tQueryType\x18\x01 \x01(\x03\x12\r\n\x05\x46ield\x18\x02 \x01(\t\x12\x11\n\tFieldType\x18\x03 \x01(\x03\x12\x11\n\tFieldVals\x18\x04 \x03(\t\",\n\x08SortInfo\x12\r\n\x05\x46ield\x18\x01 \x01(\t\x12\x11\n\tOrderType\x18\x02 \x01(\t\"\xd9\x01\n\x0cResourceInfo\x12\x0c\n\x04Type\x18\x01 \x01(\t\x12\r\n\x05Table\x18\x02 \x01(\t\x12\x0c\n\x04Topk\x18\x03 \x01(\x03\x12\x0f\n\x07Version\x18\x04 \x01(\t\x12\x14\n\x0cTargetFields\x18\x05 \x03(\t\x12&\n\x0bQueryFields\x18\x06 \x03(\x0b\x32\x11.proto.QueryField\x12\"\n\tSortInfos\x18\x07 \x03(\x0b\x32\x0f.proto.SortInfo\x12\x14\n\x0cResourceAddr\x18\x08 \x01(\t\x12\x15\n\rRelevantTable\x18\t \x01(\t\"\x9c\x01\n\rUserKeyPrefix\x12\x12\n\nUserPrefix\x18\x01 \x01(\t\x12\x12\n\nItemPrefix\x18\x02 \x01(\t\x12\x36\n\x13UserBehaviorPrefixs\x18\x03 \x03(\x0b\x32\x19.proto.UserBehaviorPrefix\x12+\n\x0bUserMapping\x18\x04 \x01(\x0b\x32\x16.proto.UserMappingInfo\"=\n\x12UserBehaviorPrefix\x12\x19\n\x11\x42\x65haviorKeyPrefix\x18\x01 \x01(\t\x12\x0c\n\x04Topk\x18\x02 \x01(\x05\"?\n\x0fUserMappingInfo\x12\x19\n\x11UserMappingPrefix\x18\x01 \x01(\t\x12\x11\n\tMemberKey\x18\x02 \x01(\t\"\x1b\n\x08\x46lowInfo\x12\x0f\n\x07\x43\x61llers\x18\x01 \x03(\tB\x12Z\x10\x41utoRecall/protob\x06proto3'
)




_QUERYFIELD = _descriptor.Descriptor(
  name='QueryField',
  full_name='proto.QueryField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='QueryType', full_name='proto.QueryField.QueryType', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Field', full_name='proto.QueryField.Field', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FieldType', full_name='proto.QueryField.FieldType', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FieldVals', full_name='proto.QueryField.FieldVals', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=130,
)


_SORTINFO = _descriptor.Descriptor(
  name='SortInfo',
  full_name='proto.SortInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Field', full_name='proto.SortInfo.Field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='OrderType', full_name='proto.SortInfo.OrderType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=176,
)


_RESOURCEINFO = _descriptor.Descriptor(
  name='ResourceInfo',
  full_name='proto.ResourceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='proto.ResourceInfo.Type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Table', full_name='proto.ResourceInfo.Table', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Topk', full_name='proto.ResourceInfo.Topk', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Version', full_name='proto.ResourceInfo.Version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TargetFields', full_name='proto.ResourceInfo.TargetFields', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='QueryFields', full_name='proto.ResourceInfo.QueryFields', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SortInfos', full_name='proto.ResourceInfo.SortInfos', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ResourceAddr', full_name='proto.ResourceInfo.ResourceAddr', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RelevantTable', full_name='proto.ResourceInfo.RelevantTable', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=396,
)


_USERKEYPREFIX = _descriptor.Descriptor(
  name='UserKeyPrefix',
  full_name='proto.UserKeyPrefix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserPrefix', full_name='proto.UserKeyPrefix.UserPrefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ItemPrefix', full_name='proto.UserKeyPrefix.ItemPrefix', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UserBehaviorPrefixs', full_name='proto.UserKeyPrefix.UserBehaviorPrefixs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UserMapping', full_name='proto.UserKeyPrefix.UserMapping', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=555,
)


_USERBEHAVIORPREFIX = _descriptor.Descriptor(
  name='UserBehaviorPrefix',
  full_name='proto.UserBehaviorPrefix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='BehaviorKeyPrefix', full_name='proto.UserBehaviorPrefix.BehaviorKeyPrefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Topk', full_name='proto.UserBehaviorPrefix.Topk', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=618,
)


_USERMAPPINGINFO = _descriptor.Descriptor(
  name='UserMappingInfo',
  full_name='proto.UserMappingInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserMappingPrefix', full_name='proto.UserMappingInfo.UserMappingPrefix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MemberKey', full_name='proto.UserMappingInfo.MemberKey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=683,
)


_FLOWINFO = _descriptor.Descriptor(
  name='FlowInfo',
  full_name='proto.FlowInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Callers', full_name='proto.FlowInfo.Callers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=712,
)

_RESOURCEINFO.fields_by_name['QueryFields'].message_type = _QUERYFIELD
_RESOURCEINFO.fields_by_name['SortInfos'].message_type = _SORTINFO
_USERKEYPREFIX.fields_by_name['UserBehaviorPrefixs'].message_type = _USERBEHAVIORPREFIX
_USERKEYPREFIX.fields_by_name['UserMapping'].message_type = _USERMAPPINGINFO
DESCRIPTOR.message_types_by_name['QueryField'] = _QUERYFIELD
DESCRIPTOR.message_types_by_name['SortInfo'] = _SORTINFO
DESCRIPTOR.message_types_by_name['ResourceInfo'] = _RESOURCEINFO
DESCRIPTOR.message_types_by_name['UserKeyPrefix'] = _USERKEYPREFIX
DESCRIPTOR.message_types_by_name['UserBehaviorPrefix'] = _USERBEHAVIORPREFIX
DESCRIPTOR.message_types_by_name['UserMappingInfo'] = _USERMAPPINGINFO
DESCRIPTOR.message_types_by_name['FlowInfo'] = _FLOWINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryField = _reflection.GeneratedProtocolMessageType('QueryField', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFIELD,
  '__module__' : 'AutoRecall.proto.common_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.QueryField)
  })
_sym_db.RegisterMessage(QueryField)

SortInfo = _reflection.GeneratedProtocolMessageType('SortInfo', (_message.Message,), {
  'DESCRIPTOR' : _SORTINFO,
  '__module__' : 'AutoRecall.proto.common_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.SortInfo)
  })
_sym_db.RegisterMessage(SortInfo)

ResourceInfo = _reflection.GeneratedProtocolMessageType('ResourceInfo', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEINFO,
  '__module__' : 'AutoRecall.proto.common_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.ResourceInfo)
  })
_sym_db.RegisterMessage(ResourceInfo)

UserKeyPrefix = _reflection.GeneratedProtocolMessageType('UserKeyPrefix', (_message.Message,), {
  'DESCRIPTOR' : _USERKEYPREFIX,
  '__module__' : 'AutoRecall.proto.common_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.UserKeyPrefix)
  })
_sym_db.RegisterMessage(UserKeyPrefix)

UserBehaviorPrefix = _reflection.GeneratedProtocolMessageType('UserBehaviorPrefix', (_message.Message,), {
  'DESCRIPTOR' : _USERBEHAVIORPREFIX,
  '__module__' : 'AutoRecall.proto.common_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.UserBehaviorPrefix)
  })
_sym_db.RegisterMessage(UserBehaviorPrefix)

UserMappingInfo = _reflection.GeneratedProtocolMessageType('UserMappingInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERMAPPINGINFO,
  '__module__' : 'AutoRecall.proto.common_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.UserMappingInfo)
  })
_sym_db.RegisterMessage(UserMappingInfo)

FlowInfo = _reflection.GeneratedProtocolMessageType('FlowInfo', (_message.Message,), {
  'DESCRIPTOR' : _FLOWINFO,
  '__module__' : 'AutoRecall.proto.common_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.FlowInfo)
  })
_sym_db.RegisterMessage(FlowInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
