# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoRecall/proto/merge_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AutoRecall/proto/merge_param.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\020AutoRecall/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"AutoRecall/proto/merge_param.proto\x12\x05proto\"D\n\x07MixInfo\x12\r\n\x05Ratio\x18\x01 \x01(\x02\x12\x0e\n\x06Weight\x18\x02 \x01(\x02\x12\x0b\n\x03\x43nt\x18\x03 \x01(\x03\x12\r\n\x05Label\x18\x04 \x01(\t\"J\n\nMergeParam\x12\x0c\n\x04Type\x18\x01 \x01(\x03\x12\x0c\n\x04TopN\x18\x02 \x01(\x03\x12 \n\x08MixInfos\x18\x03 \x03(\x0b\x32\x0e.proto.MixInfoB\x12Z\x10\x41utoRecall/protob\x06proto3'
)




_MIXINFO = _descriptor.Descriptor(
  name='MixInfo',
  full_name='proto.MixInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Ratio', full_name='proto.MixInfo.Ratio', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Weight', full_name='proto.MixInfo.Weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Cnt', full_name='proto.MixInfo.Cnt', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Label', full_name='proto.MixInfo.Label', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=113,
)


_MERGEPARAM = _descriptor.Descriptor(
  name='MergeParam',
  full_name='proto.MergeParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='proto.MergeParam.Type', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TopN', full_name='proto.MergeParam.TopN', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MixInfos', full_name='proto.MergeParam.MixInfos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=189,
)

_MERGEPARAM.fields_by_name['MixInfos'].message_type = _MIXINFO
DESCRIPTOR.message_types_by_name['MixInfo'] = _MIXINFO
DESCRIPTOR.message_types_by_name['MergeParam'] = _MERGEPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MixInfo = _reflection.GeneratedProtocolMessageType('MixInfo', (_message.Message,), {
  'DESCRIPTOR' : _MIXINFO,
  '__module__' : 'AutoRecall.proto.merge_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.MixInfo)
  })
_sym_db.RegisterMessage(MixInfo)

MergeParam = _reflection.GeneratedProtocolMessageType('MergeParam', (_message.Message,), {
  'DESCRIPTOR' : _MERGEPARAM,
  '__module__' : 'AutoRecall.proto.merge_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.MergeParam)
  })
_sym_db.RegisterMessage(MergeParam)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
