# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoRecall/proto/merge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from AutoRecall.proto import common_pb2 as AutoRecall_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AutoRecall/proto/merge.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\020AutoRecall/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x41utoRecall/proto/merge.proto\x12\x05proto\x1a\x1d\x41utoRecall/proto/common.proto\"d\n\x0cMergeRequest\x12#\n\x07ReqBase\x18\x01 \x01(\x0b\x32\x12.proto.RequestBase\x12 \n\x08MixItems\x18\x02 \x03(\x0b\x32\x0e.proto.MixItem\x12\r\n\x05Param\x18\x03 \x01(\t\"U\n\rMergeResponse\x12#\n\x07ReqBase\x18\x01 \x01(\x0b\x32\x12.proto.RequestBase\x12\x1f\n\x07MixItem\x18\x02 \x01(\x0b\x32\x0e.proto.MixItem2F\n\x0cMergeService\x12\x36\n\x07\x44oMerge\x12\x13.proto.MergeRequest\x1a\x14.proto.MergeResponse\"\x00\x42\x12Z\x10\x41utoRecall/protob\x06proto3'
  ,
  dependencies=[AutoRecall_dot_proto_dot_common__pb2.DESCRIPTOR,])




_MERGEREQUEST = _descriptor.Descriptor(
  name='MergeRequest',
  full_name='proto.MergeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqBase', full_name='proto.MergeRequest.ReqBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MixItems', full_name='proto.MergeRequest.MixItems', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Param', full_name='proto.MergeRequest.Param', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=170,
)


_MERGERESPONSE = _descriptor.Descriptor(
  name='MergeResponse',
  full_name='proto.MergeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqBase', full_name='proto.MergeResponse.ReqBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MixItem', full_name='proto.MergeResponse.MixItem', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=257,
)

_MERGEREQUEST.fields_by_name['ReqBase'].message_type = AutoRecall_dot_proto_dot_common__pb2._REQUESTBASE
_MERGEREQUEST.fields_by_name['MixItems'].message_type = AutoRecall_dot_proto_dot_common__pb2._MIXITEM
_MERGERESPONSE.fields_by_name['ReqBase'].message_type = AutoRecall_dot_proto_dot_common__pb2._REQUESTBASE
_MERGERESPONSE.fields_by_name['MixItem'].message_type = AutoRecall_dot_proto_dot_common__pb2._MIXITEM
DESCRIPTOR.message_types_by_name['MergeRequest'] = _MERGEREQUEST
DESCRIPTOR.message_types_by_name['MergeResponse'] = _MERGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MergeRequest = _reflection.GeneratedProtocolMessageType('MergeRequest', (_message.Message,), {
  'DESCRIPTOR' : _MERGEREQUEST,
  '__module__' : 'AutoRecall.proto.merge_pb2'
  # @@protoc_insertion_point(class_scope:proto.MergeRequest)
  })
_sym_db.RegisterMessage(MergeRequest)

MergeResponse = _reflection.GeneratedProtocolMessageType('MergeResponse', (_message.Message,), {
  'DESCRIPTOR' : _MERGERESPONSE,
  '__module__' : 'AutoRecall.proto.merge_pb2'
  # @@protoc_insertion_point(class_scope:proto.MergeResponse)
  })
_sym_db.RegisterMessage(MergeResponse)


DESCRIPTOR._options = None

_MERGESERVICE = _descriptor.ServiceDescriptor(
  name='MergeService',
  full_name='proto.MergeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=259,
  serialized_end=329,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoMerge',
    full_name='proto.MergeService.DoMerge',
    index=0,
    containing_service=None,
    input_type=_MERGEREQUEST,
    output_type=_MERGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MERGESERVICE)

DESCRIPTOR.services_by_name['MergeService'] = _MERGESERVICE

# @@protoc_insertion_point(module_scope)
