# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from AutoRecall.proto import rank_pb2 as AutoRecall_dot_proto_dot_rank__pb2


class RankServiceStub(object):
    """rpc 服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoRank = channel.unary_unary(
                '/proto.RankService/DoRank',
                request_serializer=AutoRecall_dot_proto_dot_rank__pb2.RankRequest.SerializeToString,
                response_deserializer=AutoRecall_dot_proto_dot_rank__pb2.RankResponse.FromString,
                )


class RankServiceServicer(object):
    """rpc 服务
    """

    def DoRank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoRank': grpc.unary_unary_rpc_method_handler(
                    servicer.DoRank,
                    request_deserializer=AutoRecall_dot_proto_dot_rank__pb2.RankRequest.FromString,
                    response_serializer=AutoRecall_dot_proto_dot_rank__pb2.RankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.RankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RankService(object):
    """rpc 服务
    """

    @staticmethod
    def DoRank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.RankService/DoRank',
            AutoRecall_dot_proto_dot_rank__pb2.RankRequest.SerializeToString,
            AutoRecall_dot_proto_dot_rank__pb2.RankResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
