# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoRecall/proto/rank_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from AutoRecall.proto import feature_pb2 as AutoRecall_dot_proto_dot_feature__pb2
from AutoRecall.proto import common_param_pb2 as AutoRecall_dot_proto_dot_common__param__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AutoRecall/proto/rank_param.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\020AutoRecall/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!AutoRecall/proto/rank_param.proto\x12\x05proto\x1a\x1e\x41utoRecall/proto/feature.proto\x1a#AutoRecall/proto/common_param.proto\"\x93\x01\n\x0bRankFeature\x12+\n\x0cuser_feature\x18\x01 \x01(\x0b\x32\x15.proto.PrefictFeature\x12+\n\x0citem_feature\x18\x02 \x01(\x0b\x32\x15.proto.PrefictFeature\x12*\n\x0bmix_feature\x18\x03 \x01(\x0b\x32\x15.proto.PrefictFeature\"}\n\tRankParam\x12\r\n\x05Label\x18\x01 \x01(\t\x12#\n\x07\x46\x65\x61ture\x18\x02 \x01(\x0b\x32\x12.proto.RankFeature\x12\x12\n\nTargetAddr\x18\x03 \x01(\t\x12(\n\nUserPrefix\x18\x04 \x01(\x0b\x32\x14.proto.UserKeyPrefix\"2\n\nXRankParam\x12$\n\nRankParams\x18\x01 \x03(\x0b\x32\x10.proto.RankParamB\x12Z\x10\x41utoRecall/protob\x06proto3'
  ,
  dependencies=[AutoRecall_dot_proto_dot_feature__pb2.DESCRIPTOR,AutoRecall_dot_proto_dot_common__param__pb2.DESCRIPTOR,])




_RANKFEATURE = _descriptor.Descriptor(
  name='RankFeature',
  full_name='proto.RankFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_feature', full_name='proto.RankFeature.user_feature', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='item_feature', full_name='proto.RankFeature.item_feature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mix_feature', full_name='proto.RankFeature.mix_feature', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=261,
)


_RANKPARAM = _descriptor.Descriptor(
  name='RankParam',
  full_name='proto.RankParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Label', full_name='proto.RankParam.Label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Feature', full_name='proto.RankParam.Feature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TargetAddr', full_name='proto.RankParam.TargetAddr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UserPrefix', full_name='proto.RankParam.UserPrefix', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=388,
)


_XRANKPARAM = _descriptor.Descriptor(
  name='XRankParam',
  full_name='proto.XRankParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RankParams', full_name='proto.XRankParam.RankParams', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=440,
)

_RANKFEATURE.fields_by_name['user_feature'].message_type = AutoRecall_dot_proto_dot_feature__pb2._PREFICTFEATURE
_RANKFEATURE.fields_by_name['item_feature'].message_type = AutoRecall_dot_proto_dot_feature__pb2._PREFICTFEATURE
_RANKFEATURE.fields_by_name['mix_feature'].message_type = AutoRecall_dot_proto_dot_feature__pb2._PREFICTFEATURE
_RANKPARAM.fields_by_name['Feature'].message_type = _RANKFEATURE
_RANKPARAM.fields_by_name['UserPrefix'].message_type = AutoRecall_dot_proto_dot_common__param__pb2._USERKEYPREFIX
_XRANKPARAM.fields_by_name['RankParams'].message_type = _RANKPARAM
DESCRIPTOR.message_types_by_name['RankFeature'] = _RANKFEATURE
DESCRIPTOR.message_types_by_name['RankParam'] = _RANKPARAM
DESCRIPTOR.message_types_by_name['XRankParam'] = _XRANKPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RankFeature = _reflection.GeneratedProtocolMessageType('RankFeature', (_message.Message,), {
  'DESCRIPTOR' : _RANKFEATURE,
  '__module__' : 'AutoRecall.proto.rank_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.RankFeature)
  })
_sym_db.RegisterMessage(RankFeature)

RankParam = _reflection.GeneratedProtocolMessageType('RankParam', (_message.Message,), {
  'DESCRIPTOR' : _RANKPARAM,
  '__module__' : 'AutoRecall.proto.rank_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.RankParam)
  })
_sym_db.RegisterMessage(RankParam)

XRankParam = _reflection.GeneratedProtocolMessageType('XRankParam', (_message.Message,), {
  'DESCRIPTOR' : _XRANKPARAM,
  '__module__' : 'AutoRecall.proto.rank_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.XRankParam)
  })
_sym_db.RegisterMessage(XRankParam)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
