# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoRecall/proto/rank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from AutoRecall.proto import common_pb2 as AutoRecall_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AutoRecall/proto/rank.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\020AutoRecall/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1b\x41utoRecall/proto/rank.proto\x12\x05proto\x1a\x1d\x41utoRecall/proto/common.proto\"b\n\x0bRankRequest\x12#\n\x07ReqBase\x18\x01 \x01(\x0b\x32\x12.proto.RequestBase\x12\x1f\n\x07MixItem\x18\x02 \x01(\x0b\x32\x0e.proto.MixItem\x12\r\n\x05Param\x18\x03 \x01(\t\"T\n\x0cRankResponse\x12#\n\x07ReqBase\x18\x01 \x01(\x0b\x32\x12.proto.RequestBase\x12\x1f\n\x07MixItem\x18\x02 \x01(\x0b\x32\x0e.proto.MixItem2B\n\x0bRankService\x12\x33\n\x06\x44oRank\x12\x12.proto.RankRequest\x1a\x13.proto.RankResponse\"\x00\x42\x12Z\x10\x41utoRecall/protob\x06proto3'
  ,
  dependencies=[AutoRecall_dot_proto_dot_common__pb2.DESCRIPTOR,])




_RANKREQUEST = _descriptor.Descriptor(
  name='RankRequest',
  full_name='proto.RankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqBase', full_name='proto.RankRequest.ReqBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MixItem', full_name='proto.RankRequest.MixItem', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Param', full_name='proto.RankRequest.Param', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=167,
)


_RANKRESPONSE = _descriptor.Descriptor(
  name='RankResponse',
  full_name='proto.RankResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqBase', full_name='proto.RankResponse.ReqBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MixItem', full_name='proto.RankResponse.MixItem', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=253,
)

_RANKREQUEST.fields_by_name['ReqBase'].message_type = AutoRecall_dot_proto_dot_common__pb2._REQUESTBASE
_RANKREQUEST.fields_by_name['MixItem'].message_type = AutoRecall_dot_proto_dot_common__pb2._MIXITEM
_RANKRESPONSE.fields_by_name['ReqBase'].message_type = AutoRecall_dot_proto_dot_common__pb2._REQUESTBASE
_RANKRESPONSE.fields_by_name['MixItem'].message_type = AutoRecall_dot_proto_dot_common__pb2._MIXITEM
DESCRIPTOR.message_types_by_name['RankRequest'] = _RANKREQUEST
DESCRIPTOR.message_types_by_name['RankResponse'] = _RANKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RankRequest = _reflection.GeneratedProtocolMessageType('RankRequest', (_message.Message,), {
  'DESCRIPTOR' : _RANKREQUEST,
  '__module__' : 'AutoRecall.proto.rank_pb2'
  # @@protoc_insertion_point(class_scope:proto.RankRequest)
  })
_sym_db.RegisterMessage(RankRequest)

RankResponse = _reflection.GeneratedProtocolMessageType('RankResponse', (_message.Message,), {
  'DESCRIPTOR' : _RANKRESPONSE,
  '__module__' : 'AutoRecall.proto.rank_pb2'
  # @@protoc_insertion_point(class_scope:proto.RankResponse)
  })
_sym_db.RegisterMessage(RankResponse)


DESCRIPTOR._options = None

_RANKSERVICE = _descriptor.ServiceDescriptor(
  name='RankService',
  full_name='proto.RankService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=255,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoRank',
    full_name='proto.RankService.DoRank',
    index=0,
    containing_service=None,
    input_type=_RANKREQUEST,
    output_type=_RANKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RANKSERVICE)

DESCRIPTOR.services_by_name['RankService'] = _RANKSERVICE

# @@protoc_insertion_point(module_scope)
