# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from AutoRecall.proto import recall_pb2 as AutoRecall_dot_proto_dot_recall__pb2


class RecallServiceStub(object):
    """rpc 服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoRecall = channel.unary_unary(
                '/proto.RecallService/DoRecall',
                request_serializer=AutoRecall_dot_proto_dot_recall__pb2.RecallRequest.SerializeToString,
                response_deserializer=AutoRecall_dot_proto_dot_recall__pb2.RecallResponse.FromString,
                )


class RecallServiceServicer(object):
    """rpc 服务
    """

    def DoRecall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecallServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoRecall': grpc.unary_unary_rpc_method_handler(
                    servicer.DoRecall,
                    request_deserializer=AutoRecall_dot_proto_dot_recall__pb2.RecallRequest.FromString,
                    response_serializer=AutoRecall_dot_proto_dot_recall__pb2.RecallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.RecallService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecallService(object):
    """rpc 服务
    """

    @staticmethod
    def DoRecall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.RecallService/DoRecall',
            AutoRecall_dot_proto_dot_recall__pb2.RecallRequest.SerializeToString,
            AutoRecall_dot_proto_dot_recall__pb2.RecallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
