# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoRecall/proto/recall.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from AutoRecall.proto import common_pb2 as AutoRecall_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AutoRecall/proto/recall.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\020AutoRecall/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x41utoRecall/proto/recall.proto\x12\x05proto\x1a\x1d\x41utoRecall/proto/common.proto\"d\n\rRecallRequest\x12#\n\x07ReqBase\x18\x01 \x01(\x0b\x32\x12.proto.RequestBase\x12\x1f\n\x07MixItem\x18\x02 \x01(\x0b\x32\x0e.proto.MixItem\x12\r\n\x05Param\x18\x03 \x01(\t\"V\n\x0eRecallResponse\x12#\n\x07ReqBase\x18\x01 \x01(\x0b\x32\x12.proto.RequestBase\x12\x1f\n\x07MixItem\x18\x02 \x01(\x0b\x32\x0e.proto.MixItem2J\n\rRecallService\x12\x39\n\x08\x44oRecall\x12\x14.proto.RecallRequest\x1a\x15.proto.RecallResponse\"\x00\x42\x12Z\x10\x41utoRecall/protob\x06proto3'
  ,
  dependencies=[AutoRecall_dot_proto_dot_common__pb2.DESCRIPTOR,])




_RECALLREQUEST = _descriptor.Descriptor(
  name='RecallRequest',
  full_name='proto.RecallRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqBase', full_name='proto.RecallRequest.ReqBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MixItem', full_name='proto.RecallRequest.MixItem', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Param', full_name='proto.RecallRequest.Param', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=171,
)


_RECALLRESPONSE = _descriptor.Descriptor(
  name='RecallResponse',
  full_name='proto.RecallResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqBase', full_name='proto.RecallResponse.ReqBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MixItem', full_name='proto.RecallResponse.MixItem', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=259,
)

_RECALLREQUEST.fields_by_name['ReqBase'].message_type = AutoRecall_dot_proto_dot_common__pb2._REQUESTBASE
_RECALLREQUEST.fields_by_name['MixItem'].message_type = AutoRecall_dot_proto_dot_common__pb2._MIXITEM
_RECALLRESPONSE.fields_by_name['ReqBase'].message_type = AutoRecall_dot_proto_dot_common__pb2._REQUESTBASE
_RECALLRESPONSE.fields_by_name['MixItem'].message_type = AutoRecall_dot_proto_dot_common__pb2._MIXITEM
DESCRIPTOR.message_types_by_name['RecallRequest'] = _RECALLREQUEST
DESCRIPTOR.message_types_by_name['RecallResponse'] = _RECALLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecallRequest = _reflection.GeneratedProtocolMessageType('RecallRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECALLREQUEST,
  '__module__' : 'AutoRecall.proto.recall_pb2'
  # @@protoc_insertion_point(class_scope:proto.RecallRequest)
  })
_sym_db.RegisterMessage(RecallRequest)

RecallResponse = _reflection.GeneratedProtocolMessageType('RecallResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECALLRESPONSE,
  '__module__' : 'AutoRecall.proto.recall_pb2'
  # @@protoc_insertion_point(class_scope:proto.RecallResponse)
  })
_sym_db.RegisterMessage(RecallResponse)


DESCRIPTOR._options = None

_RECALLSERVICE = _descriptor.ServiceDescriptor(
  name='RecallService',
  full_name='proto.RecallService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=261,
  serialized_end=335,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoRecall',
    full_name='proto.RecallService.DoRecall',
    index=0,
    containing_service=None,
    input_type=_RECALLREQUEST,
    output_type=_RECALLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECALLSERVICE)

DESCRIPTOR.services_by_name['RecallService'] = _RECALLSERVICE

# @@protoc_insertion_point(module_scope)
