# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from AutoRecall.proto import rerank_pb2 as AutoRecall_dot_proto_dot_rerank__pb2


class RerankServiceStub(object):
    """rpc 服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoRerank = channel.unary_unary(
                '/proto.RerankService/DoRerank',
                request_serializer=AutoRecall_dot_proto_dot_rerank__pb2.RerankRequest.SerializeToString,
                response_deserializer=AutoRecall_dot_proto_dot_rerank__pb2.RerankResponse.FromString,
                )


class RerankServiceServicer(object):
    """rpc 服务
    """

    def DoRerank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RerankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoRerank': grpc.unary_unary_rpc_method_handler(
                    servicer.DoRerank,
                    request_deserializer=AutoRecall_dot_proto_dot_rerank__pb2.RerankRequest.FromString,
                    response_serializer=AutoRecall_dot_proto_dot_rerank__pb2.RerankResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.RerankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RerankService(object):
    """rpc 服务
    """

    @staticmethod
    def DoRerank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.RerankService/DoRerank',
            AutoRecall_dot_proto_dot_rerank__pb2.RerankRequest.SerializeToString,
            AutoRecall_dot_proto_dot_rerank__pb2.RerankResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
