# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoRecall/proto/rerank_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from AutoRecall.proto import common_param_pb2 as AutoRecall_dot_proto_dot_common__param__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AutoRecall/proto/rerank_param.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\020AutoRecall/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#AutoRecall/proto/rerank_param.proto\x12\x05proto\x1a#AutoRecall/proto/common_param.proto\"\t\n\x07\x46ormula\";\n\nWeightInfo\x12\x0c\n\x04Type\x18\x01 \x01(\x03\x12\x1f\n\x07\x46ormula\x18\x02 \x01(\x0b\x32\x0e.proto.Formula\"\x9c\x01\n\x0bRerankParam\x12\r\n\x05Lable\x18\x01 \x01(\t\x12*\n\rFilterResInfo\x18\x02 \x01(\x0b\x32\x13.proto.ResourceInfo\x12/\n\x12SupplementResInfos\x18\x03 \x03(\x0b\x32\x13.proto.ResourceInfo\x12!\n\x08\x46lowinfo\x18\x04 \x01(\x0b\x32\x0f.proto.FlowInfo\"8\n\x0cXRerankParam\x12(\n\x0cRerankParams\x18\x01 \x03(\x0b\x32\x12.proto.RerankParamB\x12Z\x10\x41utoRecall/protob\x06proto3'
  ,
  dependencies=[AutoRecall_dot_proto_dot_common__param__pb2.DESCRIPTOR,])




_FORMULA = _descriptor.Descriptor(
  name='Formula',
  full_name='proto.Formula',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=92,
)


_WEIGHTINFO = _descriptor.Descriptor(
  name='WeightInfo',
  full_name='proto.WeightInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Type', full_name='proto.WeightInfo.Type', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Formula', full_name='proto.WeightInfo.Formula', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=153,
)


_RERANKPARAM = _descriptor.Descriptor(
  name='RerankParam',
  full_name='proto.RerankParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Lable', full_name='proto.RerankParam.Lable', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FilterResInfo', full_name='proto.RerankParam.FilterResInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SupplementResInfos', full_name='proto.RerankParam.SupplementResInfos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Flowinfo', full_name='proto.RerankParam.Flowinfo', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=312,
)


_XRERANKPARAM = _descriptor.Descriptor(
  name='XRerankParam',
  full_name='proto.XRerankParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RerankParams', full_name='proto.XRerankParam.RerankParams', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=370,
)

_WEIGHTINFO.fields_by_name['Formula'].message_type = _FORMULA
_RERANKPARAM.fields_by_name['FilterResInfo'].message_type = AutoRecall_dot_proto_dot_common__param__pb2._RESOURCEINFO
_RERANKPARAM.fields_by_name['SupplementResInfos'].message_type = AutoRecall_dot_proto_dot_common__param__pb2._RESOURCEINFO
_RERANKPARAM.fields_by_name['Flowinfo'].message_type = AutoRecall_dot_proto_dot_common__param__pb2._FLOWINFO
_XRERANKPARAM.fields_by_name['RerankParams'].message_type = _RERANKPARAM
DESCRIPTOR.message_types_by_name['Formula'] = _FORMULA
DESCRIPTOR.message_types_by_name['WeightInfo'] = _WEIGHTINFO
DESCRIPTOR.message_types_by_name['RerankParam'] = _RERANKPARAM
DESCRIPTOR.message_types_by_name['XRerankParam'] = _XRERANKPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Formula = _reflection.GeneratedProtocolMessageType('Formula', (_message.Message,), {
  'DESCRIPTOR' : _FORMULA,
  '__module__' : 'AutoRecall.proto.rerank_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.Formula)
  })
_sym_db.RegisterMessage(Formula)

WeightInfo = _reflection.GeneratedProtocolMessageType('WeightInfo', (_message.Message,), {
  'DESCRIPTOR' : _WEIGHTINFO,
  '__module__' : 'AutoRecall.proto.rerank_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.WeightInfo)
  })
_sym_db.RegisterMessage(WeightInfo)

RerankParam = _reflection.GeneratedProtocolMessageType('RerankParam', (_message.Message,), {
  'DESCRIPTOR' : _RERANKPARAM,
  '__module__' : 'AutoRecall.proto.rerank_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.RerankParam)
  })
_sym_db.RegisterMessage(RerankParam)

XRerankParam = _reflection.GeneratedProtocolMessageType('XRerankParam', (_message.Message,), {
  'DESCRIPTOR' : _XRERANKPARAM,
  '__module__' : 'AutoRecall.proto.rerank_param_pb2'
  # @@protoc_insertion_point(class_scope:proto.XRerankParam)
  })
_sym_db.RegisterMessage(XRerankParam)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
