# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoRecall/proto/rerank.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from AutoRecall.proto import common_pb2 as AutoRecall_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AutoRecall/proto/rerank.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\020AutoRecall/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x41utoRecall/proto/rerank.proto\x12\x05proto\x1a\x1d\x41utoRecall/proto/common.proto\"d\n\rRerankRequest\x12#\n\x07ReqBase\x18\x01 \x01(\x0b\x32\x12.proto.RequestBase\x12\x1f\n\x07MixItem\x18\x02 \x01(\x0b\x32\x0e.proto.MixItem\x12\r\n\x05Param\x18\x03 \x01(\t\"V\n\x0eRerankResponse\x12#\n\x07ReqBase\x18\x01 \x01(\x0b\x32\x12.proto.RequestBase\x12\x1f\n\x07MixItem\x18\x02 \x01(\x0b\x32\x0e.proto.MixItem2J\n\rRerankService\x12\x39\n\x08\x44oRerank\x12\x14.proto.RerankRequest\x1a\x15.proto.RerankResponse\"\x00\x42\x12Z\x10\x41utoRecall/protob\x06proto3'
  ,
  dependencies=[AutoRecall_dot_proto_dot_common__pb2.DESCRIPTOR,])




_RERANKREQUEST = _descriptor.Descriptor(
  name='RerankRequest',
  full_name='proto.RerankRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqBase', full_name='proto.RerankRequest.ReqBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MixItem', full_name='proto.RerankRequest.MixItem', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Param', full_name='proto.RerankRequest.Param', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=171,
)


_RERANKRESPONSE = _descriptor.Descriptor(
  name='RerankResponse',
  full_name='proto.RerankResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqBase', full_name='proto.RerankResponse.ReqBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MixItem', full_name='proto.RerankResponse.MixItem', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=259,
)

_RERANKREQUEST.fields_by_name['ReqBase'].message_type = AutoRecall_dot_proto_dot_common__pb2._REQUESTBASE
_RERANKREQUEST.fields_by_name['MixItem'].message_type = AutoRecall_dot_proto_dot_common__pb2._MIXITEM
_RERANKRESPONSE.fields_by_name['ReqBase'].message_type = AutoRecall_dot_proto_dot_common__pb2._REQUESTBASE
_RERANKRESPONSE.fields_by_name['MixItem'].message_type = AutoRecall_dot_proto_dot_common__pb2._MIXITEM
DESCRIPTOR.message_types_by_name['RerankRequest'] = _RERANKREQUEST
DESCRIPTOR.message_types_by_name['RerankResponse'] = _RERANKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RerankRequest = _reflection.GeneratedProtocolMessageType('RerankRequest', (_message.Message,), {
  'DESCRIPTOR' : _RERANKREQUEST,
  '__module__' : 'AutoRecall.proto.rerank_pb2'
  # @@protoc_insertion_point(class_scope:proto.RerankRequest)
  })
_sym_db.RegisterMessage(RerankRequest)

RerankResponse = _reflection.GeneratedProtocolMessageType('RerankResponse', (_message.Message,), {
  'DESCRIPTOR' : _RERANKRESPONSE,
  '__module__' : 'AutoRecall.proto.rerank_pb2'
  # @@protoc_insertion_point(class_scope:proto.RerankResponse)
  })
_sym_db.RegisterMessage(RerankResponse)


DESCRIPTOR._options = None

_RERANKSERVICE = _descriptor.ServiceDescriptor(
  name='RerankService',
  full_name='proto.RerankService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=261,
  serialized_end=335,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoRerank',
    full_name='proto.RerankService.DoRerank',
    index=0,
    containing_service=None,
    input_type=_RERANKREQUEST,
    output_type=_RERANKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RERANKSERVICE)

DESCRIPTOR.services_by_name['RerankService'] = _RERANKSERVICE

# @@protoc_insertion_point(module_scope)
