# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AutoRecall/proto/vengine.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from AutoRecall.proto import common_pb2 as AutoRecall_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AutoRecall/proto/vengine.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\020AutoRecall/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x41utoRecall/proto/vengine.proto\x12\x05proto\x1a\x1d\x41utoRecall/proto/common.proto\"`\n\x10VecEngineRequest\x12\x0c\n\x04Topk\x18\x01 \x01(\x05\x12\x12\n\nCollection\x18\x02 \x01(\t\x12\x1a\n\x05Items\x18\x03 \x03(\x0b\x32\x0b.proto.Item\x12\x0e\n\x06NProbe\x18\x04 \x01(\x05\">\n\x11VecEngineResponse\x12\r\n\x05State\x18\x01 \x01(\x05\x12\x1a\n\x05Items\x18\x02 \x03(\x0b\x32\x0b.proto.Item\"0\n\rEmbeddingInfo\x12\x0e\n\x06ItemId\x18\x01 \x01(\t\x12\x0f\n\x07\x45mbVals\x18\x02 \x03(\x02\"d\n\x13UpdateVectorRequest\x12\x11\n\tDimension\x18\x01 \x01(\x05\x12\x12\n\nCollection\x18\x02 \x01(\t\x12&\n\x08\x45mbInfos\x18\x03 \x03(\x0b\x32\x14.proto.EmbeddingInfo\"7\n\x14UpdateVectorResponse\x12\r\n\x05State\x18\x01 \x01(\x05\x12\x10\n\x08\x45rrorMsg\x18\x02 \x01(\t\"J\n\x17\x43reateCollectionRequest\x12\x16\n\x0e\x43ollectionName\x18\x01 \x01(\t\x12\x17\n\x0fVectorDimension\x18\x02 \x01(\x05\";\n\x18\x43reateCollectionResponse\x12\r\n\x05State\x18\x01 \x01(\x05\x12\x10\n\x08\x45rrorMsg\x18\x02 \x01(\t\">\n\x15\x44ropCollectionRequest\x12\x16\n\x0e\x43ollectionName\x18\x01 \x01(\t\x12\r\n\x05Token\x18\x03 \x01(\t\"9\n\x16\x44ropCollectionResponse\x12\r\n\x05State\x18\x01 \x01(\x05\x12\x10\n\x08\x45rrorMsg\x18\x02 \x01(\t\"]\n\x15SearchByVectorRequest\x12+\n\nVEngineReq\x18\x01 \x01(\x0b\x32\x17.proto.VecEngineRequest\x12\x17\n\x0fQueryCollection\x18\x02 \x01(\t2\x9a\x03\n\x10VecEngineService\x12?\n\x08\x44oSearch\x12\x17.proto.VecEngineRequest\x1a\x18.proto.VecEngineResponse\"\x00\x12K\n\x0e\x44oUpdateVector\x12\x1a.proto.UpdateVectorRequest\x1a\x1b.proto.UpdateVectorResponse\"\x00\x12W\n\x12\x44oCreateCollection\x12\x1e.proto.CreateCollectionRequest\x1a\x1f.proto.CreateCollectionResponse\"\x00\x12Q\n\x10\x44oDropCollection\x12\x1c.proto.DropCollectionRequest\x1a\x1d.proto.DropCollectionResponse\"\x00\x12L\n\x10\x44oSearchByVector\x12\x1c.proto.SearchByVectorRequest\x1a\x18.proto.VecEngineResponse\"\x00\x42\x12Z\x10\x41utoRecall/protob\x06proto3'
  ,
  dependencies=[AutoRecall_dot_proto_dot_common__pb2.DESCRIPTOR,])




_VECENGINEREQUEST = _descriptor.Descriptor(
  name='VecEngineRequest',
  full_name='proto.VecEngineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Topk', full_name='proto.VecEngineRequest.Topk', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Collection', full_name='proto.VecEngineRequest.Collection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Items', full_name='proto.VecEngineRequest.Items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NProbe', full_name='proto.VecEngineRequest.NProbe', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=168,
)


_VECENGINERESPONSE = _descriptor.Descriptor(
  name='VecEngineResponse',
  full_name='proto.VecEngineResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='State', full_name='proto.VecEngineResponse.State', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Items', full_name='proto.VecEngineResponse.Items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=232,
)


_EMBEDDINGINFO = _descriptor.Descriptor(
  name='EmbeddingInfo',
  full_name='proto.EmbeddingInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ItemId', full_name='proto.EmbeddingInfo.ItemId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EmbVals', full_name='proto.EmbeddingInfo.EmbVals', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=282,
)


_UPDATEVECTORREQUEST = _descriptor.Descriptor(
  name='UpdateVectorRequest',
  full_name='proto.UpdateVectorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Dimension', full_name='proto.UpdateVectorRequest.Dimension', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Collection', full_name='proto.UpdateVectorRequest.Collection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EmbInfos', full_name='proto.UpdateVectorRequest.EmbInfos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=384,
)


_UPDATEVECTORRESPONSE = _descriptor.Descriptor(
  name='UpdateVectorResponse',
  full_name='proto.UpdateVectorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='State', full_name='proto.UpdateVectorResponse.State', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ErrorMsg', full_name='proto.UpdateVectorResponse.ErrorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=441,
)


_CREATECOLLECTIONREQUEST = _descriptor.Descriptor(
  name='CreateCollectionRequest',
  full_name='proto.CreateCollectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='CollectionName', full_name='proto.CreateCollectionRequest.CollectionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='VectorDimension', full_name='proto.CreateCollectionRequest.VectorDimension', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=517,
)


_CREATECOLLECTIONRESPONSE = _descriptor.Descriptor(
  name='CreateCollectionResponse',
  full_name='proto.CreateCollectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='State', full_name='proto.CreateCollectionResponse.State', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ErrorMsg', full_name='proto.CreateCollectionResponse.ErrorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=578,
)


_DROPCOLLECTIONREQUEST = _descriptor.Descriptor(
  name='DropCollectionRequest',
  full_name='proto.DropCollectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='CollectionName', full_name='proto.DropCollectionRequest.CollectionName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Token', full_name='proto.DropCollectionRequest.Token', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=642,
)


_DROPCOLLECTIONRESPONSE = _descriptor.Descriptor(
  name='DropCollectionResponse',
  full_name='proto.DropCollectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='State', full_name='proto.DropCollectionResponse.State', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ErrorMsg', full_name='proto.DropCollectionResponse.ErrorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=644,
  serialized_end=701,
)


_SEARCHBYVECTORREQUEST = _descriptor.Descriptor(
  name='SearchByVectorRequest',
  full_name='proto.SearchByVectorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='VEngineReq', full_name='proto.SearchByVectorRequest.VEngineReq', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='QueryCollection', full_name='proto.SearchByVectorRequest.QueryCollection', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=703,
  serialized_end=796,
)

_VECENGINEREQUEST.fields_by_name['Items'].message_type = AutoRecall_dot_proto_dot_common__pb2._ITEM
_VECENGINERESPONSE.fields_by_name['Items'].message_type = AutoRecall_dot_proto_dot_common__pb2._ITEM
_UPDATEVECTORREQUEST.fields_by_name['EmbInfos'].message_type = _EMBEDDINGINFO
_SEARCHBYVECTORREQUEST.fields_by_name['VEngineReq'].message_type = _VECENGINEREQUEST
DESCRIPTOR.message_types_by_name['VecEngineRequest'] = _VECENGINEREQUEST
DESCRIPTOR.message_types_by_name['VecEngineResponse'] = _VECENGINERESPONSE
DESCRIPTOR.message_types_by_name['EmbeddingInfo'] = _EMBEDDINGINFO
DESCRIPTOR.message_types_by_name['UpdateVectorRequest'] = _UPDATEVECTORREQUEST
DESCRIPTOR.message_types_by_name['UpdateVectorResponse'] = _UPDATEVECTORRESPONSE
DESCRIPTOR.message_types_by_name['CreateCollectionRequest'] = _CREATECOLLECTIONREQUEST
DESCRIPTOR.message_types_by_name['CreateCollectionResponse'] = _CREATECOLLECTIONRESPONSE
DESCRIPTOR.message_types_by_name['DropCollectionRequest'] = _DROPCOLLECTIONREQUEST
DESCRIPTOR.message_types_by_name['DropCollectionResponse'] = _DROPCOLLECTIONRESPONSE
DESCRIPTOR.message_types_by_name['SearchByVectorRequest'] = _SEARCHBYVECTORREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VecEngineRequest = _reflection.GeneratedProtocolMessageType('VecEngineRequest', (_message.Message,), {
  'DESCRIPTOR' : _VECENGINEREQUEST,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.VecEngineRequest)
  })
_sym_db.RegisterMessage(VecEngineRequest)

VecEngineResponse = _reflection.GeneratedProtocolMessageType('VecEngineResponse', (_message.Message,), {
  'DESCRIPTOR' : _VECENGINERESPONSE,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.VecEngineResponse)
  })
_sym_db.RegisterMessage(VecEngineResponse)

EmbeddingInfo = _reflection.GeneratedProtocolMessageType('EmbeddingInfo', (_message.Message,), {
  'DESCRIPTOR' : _EMBEDDINGINFO,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.EmbeddingInfo)
  })
_sym_db.RegisterMessage(EmbeddingInfo)

UpdateVectorRequest = _reflection.GeneratedProtocolMessageType('UpdateVectorRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEVECTORREQUEST,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.UpdateVectorRequest)
  })
_sym_db.RegisterMessage(UpdateVectorRequest)

UpdateVectorResponse = _reflection.GeneratedProtocolMessageType('UpdateVectorResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEVECTORRESPONSE,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.UpdateVectorResponse)
  })
_sym_db.RegisterMessage(UpdateVectorResponse)

CreateCollectionRequest = _reflection.GeneratedProtocolMessageType('CreateCollectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATECOLLECTIONREQUEST,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.CreateCollectionRequest)
  })
_sym_db.RegisterMessage(CreateCollectionRequest)

CreateCollectionResponse = _reflection.GeneratedProtocolMessageType('CreateCollectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATECOLLECTIONRESPONSE,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.CreateCollectionResponse)
  })
_sym_db.RegisterMessage(CreateCollectionResponse)

DropCollectionRequest = _reflection.GeneratedProtocolMessageType('DropCollectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DROPCOLLECTIONREQUEST,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.DropCollectionRequest)
  })
_sym_db.RegisterMessage(DropCollectionRequest)

DropCollectionResponse = _reflection.GeneratedProtocolMessageType('DropCollectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _DROPCOLLECTIONRESPONSE,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.DropCollectionResponse)
  })
_sym_db.RegisterMessage(DropCollectionResponse)

SearchByVectorRequest = _reflection.GeneratedProtocolMessageType('SearchByVectorRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYVECTORREQUEST,
  '__module__' : 'AutoRecall.proto.vengine_pb2'
  # @@protoc_insertion_point(class_scope:proto.SearchByVectorRequest)
  })
_sym_db.RegisterMessage(SearchByVectorRequest)


DESCRIPTOR._options = None

_VECENGINESERVICE = _descriptor.ServiceDescriptor(
  name='VecEngineService',
  full_name='proto.VecEngineService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=799,
  serialized_end=1209,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoSearch',
    full_name='proto.VecEngineService.DoSearch',
    index=0,
    containing_service=None,
    input_type=_VECENGINEREQUEST,
    output_type=_VECENGINERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DoUpdateVector',
    full_name='proto.VecEngineService.DoUpdateVector',
    index=1,
    containing_service=None,
    input_type=_UPDATEVECTORREQUEST,
    output_type=_UPDATEVECTORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DoCreateCollection',
    full_name='proto.VecEngineService.DoCreateCollection',
    index=2,
    containing_service=None,
    input_type=_CREATECOLLECTIONREQUEST,
    output_type=_CREATECOLLECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DoDropCollection',
    full_name='proto.VecEngineService.DoDropCollection',
    index=3,
    containing_service=None,
    input_type=_DROPCOLLECTIONREQUEST,
    output_type=_DROPCOLLECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DoSearchByVector',
    full_name='proto.VecEngineService.DoSearchByVector',
    index=4,
    containing_service=None,
    input_type=_SEARCHBYVECTORREQUEST,
    output_type=_VECENGINERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VECENGINESERVICE)

DESCRIPTOR.services_by_name['VecEngineService'] = _VECENGINESERVICE

# @@protoc_insertion_point(module_scope)
