FROM python:3.9

RUN pip install -i https://mirrors.ustc.edu.cn/pypi/web/simple  dask  fastapi uvicorn protobuf grpcio

COPY ./ /app
RUN mkdir -p /app/log/
EXPOSE 80
WORKDIR /app

CMD ["python3", "entrypoint.py"]