# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import realtime_rec.protobuf.etl_engine_pb2 as etl__engine__pb2


class ETLEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ItemETLRequest = channel.unary_unary(
                '/etl_engine.ETLEngine/ItemETLRequest',
                request_serializer=etl__engine__pb2.ItemETLRequestInfo.SerializeToString,
                response_deserializer=etl__engine__pb2.Response.FromString,
                )
        self.UserETLRequest = channel.unary_unary(
                '/etl_engine.ETLEngine/UserETLRequest',
                request_serializer=etl__engine__pb2.UserETLRequestInfo.SerializeToString,
                response_deserializer=etl__engine__pb2.Response.FromString,
                )
        self.BehaviorETLRequest = channel.unary_unary(
                '/etl_engine.ETLEngine/BehaviorETLRequest',
                request_serializer=etl__engine__pb2.BehaviorETLRequestInfo.SerializeToString,
                response_deserializer=etl__engine__pb2.Response.FromString,
                )
        self.JoinRequest = channel.unary_unary(
                '/etl_engine.ETLEngine/JoinRequest',
                request_serializer=etl__engine__pb2.JoinRequestInfo.SerializeToString,
                response_deserializer=etl__engine__pb2.Response.FromString,
                )


class ETLEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ItemETLRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserETLRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BehaviorETLRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ETLEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ItemETLRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.ItemETLRequest,
                    request_deserializer=etl__engine__pb2.ItemETLRequestInfo.FromString,
                    response_serializer=etl__engine__pb2.Response.SerializeToString,
            ),
            'UserETLRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.UserETLRequest,
                    request_deserializer=etl__engine__pb2.UserETLRequestInfo.FromString,
                    response_serializer=etl__engine__pb2.Response.SerializeToString,
            ),
            'BehaviorETLRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.BehaviorETLRequest,
                    request_deserializer=etl__engine__pb2.BehaviorETLRequestInfo.FromString,
                    response_serializer=etl__engine__pb2.Response.SerializeToString,
            ),
            'JoinRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinRequest,
                    request_deserializer=etl__engine__pb2.JoinRequestInfo.FromString,
                    response_serializer=etl__engine__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'etl_engine.ETLEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ETLEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ItemETLRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/etl_engine.ETLEngine/ItemETLRequest',
            etl__engine__pb2.ItemETLRequestInfo.SerializeToString,
            etl__engine__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UserETLRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/etl_engine.ETLEngine/UserETLRequest',
            etl__engine__pb2.UserETLRequestInfo.SerializeToString,
            etl__engine__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BehaviorETLRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/etl_engine.ETLEngine/BehaviorETLRequest',
            etl__engine__pb2.BehaviorETLRequestInfo.SerializeToString,
            etl__engine__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/etl_engine.ETLEngine/JoinRequest',
            etl__engine__pb2.JoinRequestInfo.SerializeToString,
            etl__engine__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
