# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: etl_engine.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='etl_engine.proto',
  package='etl_engine',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x65tl_engine.proto\x12\netl_engine\"L\n\x0fRequestBaseInfo\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x10\n\x08scene_id\x18\x03 \x01(\t\"L\n\x12ItemETLRequestInfo\x12\x36\n\x11request_base_info\x18\x01 \x01(\x0b\x32\x1b.etl_engine.RequestBaseInfo\"L\n\x12UserETLRequestInfo\x12\x36\n\x11request_base_info\x18\x01 \x01(\x0b\x32\x1b.etl_engine.RequestBaseInfo\"P\n\x16\x42\x65haviorETLRequestInfo\x12\x36\n\x11request_base_info\x18\x01 \x01(\x0b\x32\x1b.etl_engine.RequestBaseInfo\"I\n\x0fJoinRequestInfo\x12\x36\n\x11request_base_info\x18\x01 \x01(\x0b\x32\x1b.etl_engine.RequestBaseInfo\"!\n\x08Response\x12\x15\n\rresponse_info\x18\x01 \x01(\x05\x32\xb5\x02\n\tETLEngine\x12H\n\x0eItemETLRequest\x12\x1e.etl_engine.ItemETLRequestInfo\x1a\x14.etl_engine.Response\"\x00\x12H\n\x0eUserETLRequest\x12\x1e.etl_engine.UserETLRequestInfo\x1a\x14.etl_engine.Response\"\x00\x12P\n\x12\x42\x65haviorETLRequest\x12\".etl_engine.BehaviorETLRequestInfo\x1a\x14.etl_engine.Response\"\x00\x12\x42\n\x0bJoinRequest\x12\x1b.etl_engine.JoinRequestInfo\x1a\x14.etl_engine.Response\"\x00\x62\x06proto3'
)




_REQUESTBASEINFO = _descriptor.Descriptor(
  name='RequestBaseInfo',
  full_name='etl_engine.RequestBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='etl_engine.RequestBaseInfo.customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='etl_engine.RequestBaseInfo.project_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scene_id', full_name='etl_engine.RequestBaseInfo.scene_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=108,
)


_ITEMETLREQUESTINFO = _descriptor.Descriptor(
  name='ItemETLRequestInfo',
  full_name='etl_engine.ItemETLRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='etl_engine.ItemETLRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=186,
)


_USERETLREQUESTINFO = _descriptor.Descriptor(
  name='UserETLRequestInfo',
  full_name='etl_engine.UserETLRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='etl_engine.UserETLRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=264,
)


_BEHAVIORETLREQUESTINFO = _descriptor.Descriptor(
  name='BehaviorETLRequestInfo',
  full_name='etl_engine.BehaviorETLRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='etl_engine.BehaviorETLRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=346,
)


_JOINREQUESTINFO = _descriptor.Descriptor(
  name='JoinRequestInfo',
  full_name='etl_engine.JoinRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='etl_engine.JoinRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=421,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='etl_engine.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_info', full_name='etl_engine.Response.response_info', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=456,
)

_ITEMETLREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
_USERETLREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
_BEHAVIORETLREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
_JOINREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
DESCRIPTOR.message_types_by_name['RequestBaseInfo'] = _REQUESTBASEINFO
DESCRIPTOR.message_types_by_name['ItemETLRequestInfo'] = _ITEMETLREQUESTINFO
DESCRIPTOR.message_types_by_name['UserETLRequestInfo'] = _USERETLREQUESTINFO
DESCRIPTOR.message_types_by_name['BehaviorETLRequestInfo'] = _BEHAVIORETLREQUESTINFO
DESCRIPTOR.message_types_by_name['JoinRequestInfo'] = _JOINREQUESTINFO
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestBaseInfo = _reflection.GeneratedProtocolMessageType('RequestBaseInfo', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTBASEINFO,
  '__module__' : 'etl_engine_pb2'
  # @@protoc_insertion_point(class_scope:etl_engine.RequestBaseInfo)
  })
_sym_db.RegisterMessage(RequestBaseInfo)

ItemETLRequestInfo = _reflection.GeneratedProtocolMessageType('ItemETLRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _ITEMETLREQUESTINFO,
  '__module__' : 'etl_engine_pb2'
  # @@protoc_insertion_point(class_scope:etl_engine.ItemETLRequestInfo)
  })
_sym_db.RegisterMessage(ItemETLRequestInfo)

UserETLRequestInfo = _reflection.GeneratedProtocolMessageType('UserETLRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _USERETLREQUESTINFO,
  '__module__' : 'etl_engine_pb2'
  # @@protoc_insertion_point(class_scope:etl_engine.UserETLRequestInfo)
  })
_sym_db.RegisterMessage(UserETLRequestInfo)

BehaviorETLRequestInfo = _reflection.GeneratedProtocolMessageType('BehaviorETLRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _BEHAVIORETLREQUESTINFO,
  '__module__' : 'etl_engine_pb2'
  # @@protoc_insertion_point(class_scope:etl_engine.BehaviorETLRequestInfo)
  })
_sym_db.RegisterMessage(BehaviorETLRequestInfo)

JoinRequestInfo = _reflection.GeneratedProtocolMessageType('JoinRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _JOINREQUESTINFO,
  '__module__' : 'etl_engine_pb2'
  # @@protoc_insertion_point(class_scope:etl_engine.JoinRequestInfo)
  })
_sym_db.RegisterMessage(JoinRequestInfo)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'etl_engine_pb2'
  # @@protoc_insertion_point(class_scope:etl_engine.Response)
  })
_sym_db.RegisterMessage(Response)



_ETLENGINE = _descriptor.ServiceDescriptor(
  name='ETLEngine',
  full_name='etl_engine.ETLEngine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=459,
  serialized_end=768,
  methods=[
  _descriptor.MethodDescriptor(
    name='ItemETLRequest',
    full_name='etl_engine.ETLEngine.ItemETLRequest',
    index=0,
    containing_service=None,
    input_type=_ITEMETLREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UserETLRequest',
    full_name='etl_engine.ETLEngine.UserETLRequest',
    index=1,
    containing_service=None,
    input_type=_USERETLREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BehaviorETLRequest',
    full_name='etl_engine.ETLEngine.BehaviorETLRequest',
    index=2,
    containing_service=None,
    input_type=_BEHAVIORETLREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='JoinRequest',
    full_name='etl_engine.ETLEngine.JoinRequest',
    index=3,
    containing_service=None,
    input_type=_JOINREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ETLENGINE)

DESCRIPTOR.services_by_name['ETLEngine'] = _ETLENGINE

# @@protoc_insertion_point(module_scope)
