# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nearline_engine.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nearline_engine.proto',
  package='nearline_engine',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15nearline_engine.proto\x12\x0fnearline_engine\"6\n\x0fRequestBaseInfo\x12\x13\n\x0bpipeline_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\t\"N\n\x0fOLAPRequestInfo\x12;\n\x11request_base_info\x18\x01 \x01(\x0b\x32 .nearline_engine.RequestBaseInfo\"W\n\x18TextEmbeddingRequestInfo\x12;\n\x11request_base_info\x18\x01 \x01(\x0b\x32 .nearline_engine.RequestBaseInfo\"!\n\x08Response\x12\x15\n\rresponse_info\x18\x01 \x01(\x05\x32\xbe\x01\n\x0eNearlineEngine\x12L\n\x0bOLAPRequest\x12 .nearline_engine.OLAPRequestInfo\x1a\x19.nearline_engine.Response\"\x00\x12^\n\x14TextEmbeddingRequest\x12).nearline_engine.TextEmbeddingRequestInfo\x1a\x19.nearline_engine.Response\"\x00\x62\x06proto3'
)




_REQUESTBASEINFO = _descriptor.Descriptor(
  name='RequestBaseInfo',
  full_name='nearline_engine.RequestBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipeline_id', full_name='nearline_engine.RequestBaseInfo.pipeline_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='nearline_engine.RequestBaseInfo.config', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=96,
)


_OLAPREQUESTINFO = _descriptor.Descriptor(
  name='OLAPRequestInfo',
  full_name='nearline_engine.OLAPRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='nearline_engine.OLAPRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=176,
)


_TEXTEMBEDDINGREQUESTINFO = _descriptor.Descriptor(
  name='TextEmbeddingRequestInfo',
  full_name='nearline_engine.TextEmbeddingRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='nearline_engine.TextEmbeddingRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=265,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='nearline_engine.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_info', full_name='nearline_engine.Response.response_info', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=300,
)

_OLAPREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
_TEXTEMBEDDINGREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
DESCRIPTOR.message_types_by_name['RequestBaseInfo'] = _REQUESTBASEINFO
DESCRIPTOR.message_types_by_name['OLAPRequestInfo'] = _OLAPREQUESTINFO
DESCRIPTOR.message_types_by_name['TextEmbeddingRequestInfo'] = _TEXTEMBEDDINGREQUESTINFO
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestBaseInfo = _reflection.GeneratedProtocolMessageType('RequestBaseInfo', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTBASEINFO,
  '__module__' : 'nearline_engine_pb2'
  # @@protoc_insertion_point(class_scope:nearline_engine.RequestBaseInfo)
  })
_sym_db.RegisterMessage(RequestBaseInfo)

OLAPRequestInfo = _reflection.GeneratedProtocolMessageType('OLAPRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _OLAPREQUESTINFO,
  '__module__' : 'nearline_engine_pb2'
  # @@protoc_insertion_point(class_scope:nearline_engine.OLAPRequestInfo)
  })
_sym_db.RegisterMessage(OLAPRequestInfo)

TextEmbeddingRequestInfo = _reflection.GeneratedProtocolMessageType('TextEmbeddingRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _TEXTEMBEDDINGREQUESTINFO,
  '__module__' : 'nearline_engine_pb2'
  # @@protoc_insertion_point(class_scope:nearline_engine.TextEmbeddingRequestInfo)
  })
_sym_db.RegisterMessage(TextEmbeddingRequestInfo)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'nearline_engine_pb2'
  # @@protoc_insertion_point(class_scope:nearline_engine.Response)
  })
_sym_db.RegisterMessage(Response)



_NEARLINEENGINE = _descriptor.ServiceDescriptor(
  name='NearlineEngine',
  full_name='nearline_engine.NearlineEngine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=303,
  serialized_end=493,
  methods=[
  _descriptor.MethodDescriptor(
    name='OLAPRequest',
    full_name='nearline_engine.NearlineEngine.OLAPRequest',
    index=0,
    containing_service=None,
    input_type=_OLAPREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TextEmbeddingRequest',
    full_name='nearline_engine.NearlineEngine.TextEmbeddingRequest',
    index=1,
    containing_service=None,
    input_type=_TEXTEMBEDDINGREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NEARLINEENGINE)

DESCRIPTOR.services_by_name['NearlineEngine'] = _NEARLINEENGINE

# @@protoc_insertion_point(module_scope)
