# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: offline_engine.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='offline_engine.proto',
  package='offline_engine',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14offline_engine.proto\x12\x0eoffline_engine\"L\n\x0fRequestBaseInfo\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x10\n\x08scene_id\x18\x03 \x01(\t\"X\n\x1aRankSampleMakerRequestInfo\x12:\n\x11request_base_info\x18\x01 \x01(\x0b\x32\x1f.offline_engine.RequestBaseInfo\"T\n\x16RankTrainerRequestInfo\x12:\n\x11request_base_info\x18\x01 \x01(\x0b\x32\x1f.offline_engine.RequestBaseInfo\"Z\n\x1cRecallSampleMakerRequestInfo\x12:\n\x11request_base_info\x18\x01 \x01(\x0b\x32\x1f.offline_engine.RequestBaseInfo\"V\n\x18RecallTrainerRequestInfo\x12:\n\x11request_base_info\x18\x01 \x01(\x0b\x32\x1f.offline_engine.RequestBaseInfo\"!\n\x08Response\x12\x15\n\rresponse_info\x18\x01 \x01(\x05\x32\x8f\x03\n\rOfflineEngine\x12`\n\x16RankSampleMakerRequest\x12*.offline_engine.RankSampleMakerRequestInfo\x1a\x18.offline_engine.Response\"\x00\x12X\n\x12RankTrainerRequest\x12&.offline_engine.RankTrainerRequestInfo\x1a\x18.offline_engine.Response\"\x00\x12\x64\n\x18RecallSampleMakerRequest\x12,.offline_engine.RecallSampleMakerRequestInfo\x1a\x18.offline_engine.Response\"\x00\x12\\\n\x14RecallTrainerRequest\x12(.offline_engine.RecallTrainerRequestInfo\x1a\x18.offline_engine.Response\"\x00\x62\x06proto3'
)




_REQUESTBASEINFO = _descriptor.Descriptor(
  name='RequestBaseInfo',
  full_name='offline_engine.RequestBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='offline_engine.RequestBaseInfo.customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='offline_engine.RequestBaseInfo.project_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scene_id', full_name='offline_engine.RequestBaseInfo.scene_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=116,
)


_RANKSAMPLEMAKERREQUESTINFO = _descriptor.Descriptor(
  name='RankSampleMakerRequestInfo',
  full_name='offline_engine.RankSampleMakerRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='offline_engine.RankSampleMakerRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=206,
)


_RANKTRAINERREQUESTINFO = _descriptor.Descriptor(
  name='RankTrainerRequestInfo',
  full_name='offline_engine.RankTrainerRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='offline_engine.RankTrainerRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=292,
)


_RECALLSAMPLEMAKERREQUESTINFO = _descriptor.Descriptor(
  name='RecallSampleMakerRequestInfo',
  full_name='offline_engine.RecallSampleMakerRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='offline_engine.RecallSampleMakerRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=384,
)


_RECALLTRAINERREQUESTINFO = _descriptor.Descriptor(
  name='RecallTrainerRequestInfo',
  full_name='offline_engine.RecallTrainerRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='offline_engine.RecallTrainerRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=472,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='offline_engine.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_info', full_name='offline_engine.Response.response_info', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=507,
)

_RANKSAMPLEMAKERREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
_RANKTRAINERREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
_RECALLSAMPLEMAKERREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
_RECALLTRAINERREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
DESCRIPTOR.message_types_by_name['RequestBaseInfo'] = _REQUESTBASEINFO
DESCRIPTOR.message_types_by_name['RankSampleMakerRequestInfo'] = _RANKSAMPLEMAKERREQUESTINFO
DESCRIPTOR.message_types_by_name['RankTrainerRequestInfo'] = _RANKTRAINERREQUESTINFO
DESCRIPTOR.message_types_by_name['RecallSampleMakerRequestInfo'] = _RECALLSAMPLEMAKERREQUESTINFO
DESCRIPTOR.message_types_by_name['RecallTrainerRequestInfo'] = _RECALLTRAINERREQUESTINFO
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestBaseInfo = _reflection.GeneratedProtocolMessageType('RequestBaseInfo', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTBASEINFO,
  '__module__' : 'offline_engine_pb2'
  # @@protoc_insertion_point(class_scope:offline_engine.RequestBaseInfo)
  })
_sym_db.RegisterMessage(RequestBaseInfo)

RankSampleMakerRequestInfo = _reflection.GeneratedProtocolMessageType('RankSampleMakerRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _RANKSAMPLEMAKERREQUESTINFO,
  '__module__' : 'offline_engine_pb2'
  # @@protoc_insertion_point(class_scope:offline_engine.RankSampleMakerRequestInfo)
  })
_sym_db.RegisterMessage(RankSampleMakerRequestInfo)

RankTrainerRequestInfo = _reflection.GeneratedProtocolMessageType('RankTrainerRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _RANKTRAINERREQUESTINFO,
  '__module__' : 'offline_engine_pb2'
  # @@protoc_insertion_point(class_scope:offline_engine.RankTrainerRequestInfo)
  })
_sym_db.RegisterMessage(RankTrainerRequestInfo)

RecallSampleMakerRequestInfo = _reflection.GeneratedProtocolMessageType('RecallSampleMakerRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _RECALLSAMPLEMAKERREQUESTINFO,
  '__module__' : 'offline_engine_pb2'
  # @@protoc_insertion_point(class_scope:offline_engine.RecallSampleMakerRequestInfo)
  })
_sym_db.RegisterMessage(RecallSampleMakerRequestInfo)

RecallTrainerRequestInfo = _reflection.GeneratedProtocolMessageType('RecallTrainerRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _RECALLTRAINERREQUESTINFO,
  '__module__' : 'offline_engine_pb2'
  # @@protoc_insertion_point(class_scope:offline_engine.RecallTrainerRequestInfo)
  })
_sym_db.RegisterMessage(RecallTrainerRequestInfo)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'offline_engine_pb2'
  # @@protoc_insertion_point(class_scope:offline_engine.Response)
  })
_sym_db.RegisterMessage(Response)



_OFFLINEENGINE = _descriptor.ServiceDescriptor(
  name='OfflineEngine',
  full_name='offline_engine.OfflineEngine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=510,
  serialized_end=909,
  methods=[
  _descriptor.MethodDescriptor(
    name='RankSampleMakerRequest',
    full_name='offline_engine.OfflineEngine.RankSampleMakerRequest',
    index=0,
    containing_service=None,
    input_type=_RANKSAMPLEMAKERREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RankTrainerRequest',
    full_name='offline_engine.OfflineEngine.RankTrainerRequest',
    index=1,
    containing_service=None,
    input_type=_RANKTRAINERREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RecallSampleMakerRequest',
    full_name='offline_engine.OfflineEngine.RecallSampleMakerRequest',
    index=2,
    containing_service=None,
    input_type=_RECALLSAMPLEMAKERREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RecallTrainerRequest',
    full_name='offline_engine.OfflineEngine.RecallTrainerRequest',
    index=3,
    containing_service=None,
    input_type=_RECALLTRAINERREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OFFLINEENGINE)

DESCRIPTOR.services_by_name['OfflineEngine'] = _OFFLINEENGINE

# @@protoc_insertion_point(module_scope)
