# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rank_engine.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rank_engine.proto',
  package='rankengine',
  syntax='proto3',
  serialized_options=b'Z\014./rankengine',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11rank_engine.proto\x12\nrankengine\"L\n\x0fRequestBaseInfo\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x10\n\x08scene_id\x18\x03 \x01(\t\"$\n\rRequestSample\x12\x13\n\x0b\x46\x65\x61tureList\x18\x01 \x01(\t\"\x1a\n\tScoreList\x12\r\n\x05value\x18\x01 \x01(\x02\"Y\n\x0bRequestInfo\x12\x18\n\x10RequestAlgorithm\x18\x01 \x01(\t\x12\x30\n\rRequestSample\x18\x02 \x03(\x0b\x32\x19.rankengine.RequestSample\"J\n\x08Response\x12\x14\n\x0cResponseInfo\x18\x01 \x01(\x05\x12(\n\tScoreList\x18\x02 \x03(\x0b\x32\x15.rankengine.ScoreList\"K\n\x11UpdateRequestInfo\x12\x36\n\x11request_base_info\x18\x01 \x01(\x0b\x32\x1b.rankengine.RequestBaseInfo\"&\n\x0eUpdateResponse\x12\x14\n\x0cResponseInfo\x18\x01 \x01(\x05\x32\x92\x01\n\nRankEngine\x12>\n\x0bRankRequest\x12\x17.rankengine.RequestInfo\x1a\x14.rankengine.Response\"\x00\x12\x44\n\x0bUpdateModel\x12\x1d.rankengine.UpdateRequestInfo\x1a\x14.rankengine.Response\"\x00\x42\x0eZ\x0c./rankengineb\x06proto3'
)




_REQUESTBASEINFO = _descriptor.Descriptor(
  name='RequestBaseInfo',
  full_name='rankengine.RequestBaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='rankengine.RequestBaseInfo.customer_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_id', full_name='rankengine.RequestBaseInfo.project_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scene_id', full_name='rankengine.RequestBaseInfo.scene_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=109,
)


_REQUESTSAMPLE = _descriptor.Descriptor(
  name='RequestSample',
  full_name='rankengine.RequestSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='FeatureList', full_name='rankengine.RequestSample.FeatureList', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=147,
)


_SCORELIST = _descriptor.Descriptor(
  name='ScoreList',
  full_name='rankengine.ScoreList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='rankengine.ScoreList.value', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=175,
)


_REQUESTINFO = _descriptor.Descriptor(
  name='RequestInfo',
  full_name='rankengine.RequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RequestAlgorithm', full_name='rankengine.RequestInfo.RequestAlgorithm', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RequestSample', full_name='rankengine.RequestInfo.RequestSample', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=266,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='rankengine.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResponseInfo', full_name='rankengine.Response.ResponseInfo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ScoreList', full_name='rankengine.Response.ScoreList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=342,
)


_UPDATEREQUESTINFO = _descriptor.Descriptor(
  name='UpdateRequestInfo',
  full_name='rankengine.UpdateRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_base_info', full_name='rankengine.UpdateRequestInfo.request_base_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=419,
)


_UPDATERESPONSE = _descriptor.Descriptor(
  name='UpdateResponse',
  full_name='rankengine.UpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResponseInfo', full_name='rankengine.UpdateResponse.ResponseInfo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=459,
)

_REQUESTINFO.fields_by_name['RequestSample'].message_type = _REQUESTSAMPLE
_RESPONSE.fields_by_name['ScoreList'].message_type = _SCORELIST
_UPDATEREQUESTINFO.fields_by_name['request_base_info'].message_type = _REQUESTBASEINFO
DESCRIPTOR.message_types_by_name['RequestBaseInfo'] = _REQUESTBASEINFO
DESCRIPTOR.message_types_by_name['RequestSample'] = _REQUESTSAMPLE
DESCRIPTOR.message_types_by_name['ScoreList'] = _SCORELIST
DESCRIPTOR.message_types_by_name['RequestInfo'] = _REQUESTINFO
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['UpdateRequestInfo'] = _UPDATEREQUESTINFO
DESCRIPTOR.message_types_by_name['UpdateResponse'] = _UPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestBaseInfo = _reflection.GeneratedProtocolMessageType('RequestBaseInfo', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTBASEINFO,
  '__module__' : 'rank_engine_pb2'
  # @@protoc_insertion_point(class_scope:rankengine.RequestBaseInfo)
  })
_sym_db.RegisterMessage(RequestBaseInfo)

RequestSample = _reflection.GeneratedProtocolMessageType('RequestSample', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSAMPLE,
  '__module__' : 'rank_engine_pb2'
  # @@protoc_insertion_point(class_scope:rankengine.RequestSample)
  })
_sym_db.RegisterMessage(RequestSample)

ScoreList = _reflection.GeneratedProtocolMessageType('ScoreList', (_message.Message,), {
  'DESCRIPTOR' : _SCORELIST,
  '__module__' : 'rank_engine_pb2'
  # @@protoc_insertion_point(class_scope:rankengine.ScoreList)
  })
_sym_db.RegisterMessage(ScoreList)

RequestInfo = _reflection.GeneratedProtocolMessageType('RequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTINFO,
  '__module__' : 'rank_engine_pb2'
  # @@protoc_insertion_point(class_scope:rankengine.RequestInfo)
  })
_sym_db.RegisterMessage(RequestInfo)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'rank_engine_pb2'
  # @@protoc_insertion_point(class_scope:rankengine.Response)
  })
_sym_db.RegisterMessage(Response)

UpdateRequestInfo = _reflection.GeneratedProtocolMessageType('UpdateRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUESTINFO,
  '__module__' : 'rank_engine_pb2'
  # @@protoc_insertion_point(class_scope:rankengine.UpdateRequestInfo)
  })
_sym_db.RegisterMessage(UpdateRequestInfo)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'rank_engine_pb2'
  # @@protoc_insertion_point(class_scope:rankengine.UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)


DESCRIPTOR._options = None

_RANKENGINE = _descriptor.ServiceDescriptor(
  name='RankEngine',
  full_name='rankengine.RankEngine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=462,
  serialized_end=608,
  methods=[
  _descriptor.MethodDescriptor(
    name='RankRequest',
    full_name='rankengine.RankEngine.RankRequest',
    index=0,
    containing_service=None,
    input_type=_REQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateModel',
    full_name='rankengine.RankEngine.UpdateModel',
    index=1,
    containing_service=None,
    input_type=_UPDATEREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RANKENGINE)

DESCRIPTOR.services_by_name['RankEngine'] = _RANKENGINE

# @@protoc_insertion_point(module_scope)
