# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import realtime_rec.protobuf.vec_milvus_engine_pb2 as vec__milvus__engine__pb2


class VecMilvusEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VecSearch = channel.unary_unary(
                '/vec_milvus_engine.VecMilvusEngine/VecSearch',
                request_serializer=vec__milvus__engine__pb2.VecRequestInfo.SerializeToString,
                response_deserializer=vec__milvus__engine__pb2.Response.FromString,
                )


class VecMilvusEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VecSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VecMilvusEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VecSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.VecSearch,
                    request_deserializer=vec__milvus__engine__pb2.VecRequestInfo.FromString,
                    response_serializer=vec__milvus__engine__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vec_milvus_engine.VecMilvusEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VecMilvusEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VecSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vec_milvus_engine.VecMilvusEngine/VecSearch',
            vec__milvus__engine__pb2.VecRequestInfo.SerializeToString,
            vec__milvus__engine__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
