# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vec_milvus_engine.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vec_milvus_engine.proto',
  package='vec_milvus_engine',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17vec_milvus_engine.proto\x12\x11vec_milvus_engine\"\x1b\n\x08ItemList\x12\x0f\n\x07item_id\x18\x01 \x01(\t\"x\n\x0eVecRequestInfo\x12\x13\n\x0brecall_topk\x18\x01 \x01(\x05\x12\x19\n\x11request_algorithm\x18\x02 \x01(\t\x12\x36\n\x11request_item_list\x18\x03 \x03(\x0b\x32\x1b.vec_milvus_engine.ItemList\"Z\n\x08Response\x12\x15\n\rresponse_info\x18\x01 \x01(\x05\x12\x37\n\x12response_item_list\x18\x02 \x03(\x0b\x32\x1b.vec_milvus_engine.ItemList2`\n\x0fVecMilvusEngine\x12M\n\tVecSearch\x12!.vec_milvus_engine.VecRequestInfo\x1a\x1b.vec_milvus_engine.Response\"\x00\x62\x06proto3'
)




_ITEMLIST = _descriptor.Descriptor(
  name='ItemList',
  full_name='vec_milvus_engine.ItemList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='vec_milvus_engine.ItemList.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=73,
)


_VECREQUESTINFO = _descriptor.Descriptor(
  name='VecRequestInfo',
  full_name='vec_milvus_engine.VecRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recall_topk', full_name='vec_milvus_engine.VecRequestInfo.recall_topk', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_algorithm', full_name='vec_milvus_engine.VecRequestInfo.request_algorithm', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_item_list', full_name='vec_milvus_engine.VecRequestInfo.request_item_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=195,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='vec_milvus_engine.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_info', full_name='vec_milvus_engine.Response.response_info', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response_item_list', full_name='vec_milvus_engine.Response.response_item_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=287,
)

_VECREQUESTINFO.fields_by_name['request_item_list'].message_type = _ITEMLIST
_RESPONSE.fields_by_name['response_item_list'].message_type = _ITEMLIST
DESCRIPTOR.message_types_by_name['ItemList'] = _ITEMLIST
DESCRIPTOR.message_types_by_name['VecRequestInfo'] = _VECREQUESTINFO
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ItemList = _reflection.GeneratedProtocolMessageType('ItemList', (_message.Message,), {
  'DESCRIPTOR' : _ITEMLIST,
  '__module__' : 'vec_milvus_engine_pb2'
  # @@protoc_insertion_point(class_scope:vec_milvus_engine.ItemList)
  })
_sym_db.RegisterMessage(ItemList)

VecRequestInfo = _reflection.GeneratedProtocolMessageType('VecRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _VECREQUESTINFO,
  '__module__' : 'vec_milvus_engine_pb2'
  # @@protoc_insertion_point(class_scope:vec_milvus_engine.VecRequestInfo)
  })
_sym_db.RegisterMessage(VecRequestInfo)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'vec_milvus_engine_pb2'
  # @@protoc_insertion_point(class_scope:vec_milvus_engine.Response)
  })
_sym_db.RegisterMessage(Response)



_VECMILVUSENGINE = _descriptor.ServiceDescriptor(
  name='VecMilvusEngine',
  full_name='vec_milvus_engine.VecMilvusEngine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=289,
  serialized_end=385,
  methods=[
  _descriptor.MethodDescriptor(
    name='VecSearch',
    full_name='vec_milvus_engine.VecMilvusEngine.VecSearch',
    index=0,
    containing_service=None,
    input_type=_VECREQUESTINFO,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VECMILVUSENGINE)

DESCRIPTOR.services_by_name['VecMilvusEngine'] = _VECMILVUSENGINE

# @@protoc_insertion_point(module_scope)
